"""make_content_text_nullable

Revision ID: 35815d565142
Revises: b9cf06f2220a
Create Date: 2026-02-05 17:01:25.390108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35815d565142'
down_revision: Union[str, Sequence[str], None] = 'b9cf06f2220a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content_text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
