"""Add caption to posts

Revision ID: 8cee938430f2
Revises: be9ef00b4e91
Create Date: 2026-02-03 15:11:17.987844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cee938430f2'
down_revision: Union[str, Sequence[str], None] = 'be9ef00b4e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('caption', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'caption')
    # ### end Alembic commands ###
