"""Add post cascade delete

Revision ID: b9cf06f2220a
Revises: 8cee938430f2
Create Date: 2026-02-04 14:16:31.890966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9cf06f2220a'
down_revision: Union[str, Sequence[str], None] = '8cee938430f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_post_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('likes_post_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notifications_post_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_post_id_fkey'), 'notifications', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_post_id_fkey'), 'likes', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_post_id_fkey'), 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
